In [4]:
! pip install numpy
! pip install pandas
! pip install scikit-learn
! pip install matplotlib
! pip install nltk


[notice] A new release of pip is available: 23.2.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/a6/b6/a9405484fb40746fdc6ae4502b16a9d6e53282ba5baaf9ebe2da579f68c4/matplotlib-3.10.1-cp312-cp312-win_amd64.whl.metadata
  Using cached matplotlib-3.10.1-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/01/c8/fadd0b92ffa7b5eb5949bf340a63a4a496a6930a6c37a7ba0f12acb076d6/contourpy-1.3.2-cp312-cp312-win_amd64.whl.metadata
  Using cached contourpy-1.3.2-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
  Obtaining dependency information for cycler>=0.10 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/06/5d/1be5424bb305880e1113631f49a55ea7c7da3a5


[notice] A new release of pip is available: 23.2.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.2.1 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk

In [107]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to C:\Users\user/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\user/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nlt

True

In [108]:
dataset = pd.read_csv('data/Train.csv')

In [109]:
dataset = dataset[dataset['Body'].notna() & (dataset['Body'].str.strip() != '')]

In [110]:
print(dataset)

        Id                                               Body Sentiment Type
0        1  rule 2 no metes about polarizing political top...        neutral
2        3  no politics danger now i can make a propaganda...       negative
3        4                       i am the senate gets stabbed        neutral
4        5                                  is this a suicide        neutral
5        6                                            removed        neutral
...    ...                                                ...            ...
1995  1996                       god gen alpha needs to chill        neutral
1996  1997           people when new generation does anything       positive
1997  1998                        me when minor inconvenience       negative
1998  1999  as a gen z who didn experience brain rot in we...       negative
1999  2000  ah the vine era had a boatload of cringe quote...       negative

[1772 rows x 3 columns]


In [111]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [112]:
wnl = WordNetLemmatizer()
ps = PorterStemmer()

stopword = set(stopwords.words('english'))

In [113]:
def preprocessText(text):
    text = text.lower()

    tokens = word_tokenize(text)

    filtered = [token for token in tokens if token not in stopword and token.isalpha()]

    lemmas = [wnl.lemmatize(x) for x in filtered]

    return ' '.join(lemmas)


In [114]:
dataset['processedText'] = dataset['Body'].apply(preprocessText)
dataset['processedText']

0       rule mete polarizing political topic vulnerabl...
2       politics danger make propaganda meme telling p...
3                                      senate get stabbed
4                                                 suicide
5                                                 removed
                              ...                        
1995                             god gen alpha need chill
1996                       people new generation anything
1997                                  minor inconvenience
1998    gen z experience brain rot western internet du...
1999    ah vine era boatload cringe quote middle schoo...
Name: processedText, Length: 1772, dtype: object

In [115]:
dataset['processedSentiment'] = dataset['Sentiment Type'].apply(preprocessText)

dataset['processedSentiment']

0        neutral
2       negative
3        neutral
4        neutral
5        neutral
          ...   
1995     neutral
1996    positive
1997    negative
1998    negative
1999    negative
Name: processedSentiment, Length: 1772, dtype: object

In [116]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [117]:
X = dataset['processedText']
y = dataset['processedSentiment']

In [118]:
X

0       rule mete polarizing political topic vulnerabl...
2       politics danger make propaganda meme telling p...
3                                      senate get stabbed
4                                                 suicide
5                                                 removed
                              ...                        
1995                             god gen alpha need chill
1996                       people new generation anything
1997                                  minor inconvenience
1998    gen z experience brain rot western internet du...
1999    ah vine era boatload cringe quote middle schoo...
Name: processedText, Length: 1772, dtype: object

In [119]:
y = y.str.strip().str.lower() 

In [120]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y_encoded = encoder.fit_transform(y)

In [121]:
print(np.unique(y_encoded))  

[0 1 2]


In [122]:
y_encoded

array([1, 0, 1, ..., 0, 0, 0], shape=(1772,))

In [123]:
list(encoder.inverse_transform(np.unique(y_encoded)))

['negative', 'neutral', 'positive']

In [124]:
X

0       rule mete polarizing political topic vulnerabl...
2       politics danger make propaganda meme telling p...
3                                      senate get stabbed
4                                                 suicide
5                                                 removed
                              ...                        
1995                             god gen alpha need chill
1996                       people new generation anything
1997                                  minor inconvenience
1998    gen z experience brain rot western internet du...
1999    ah vine era boatload cringe quote middle schoo...
Name: processedText, Length: 1772, dtype: object

In [125]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_df=0.9, min_df=5)

x_vect = vectorizer.fit_transform(dataset['processedText'])

In [126]:
xtrain, xtest, ytrain, ytest = train_test_split(x_vect, y_encoded, test_size=0.2, random_state=42)

In [127]:
print(y.value_counts())

processedSentiment
neutral     782
positive    632
negative    358
Name: count, dtype: int64


In [128]:
xtrain

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6841 stored elements and shape (1417, 626)>

In [129]:
ytrain

array([1, 2, 1, ..., 0, 1, 2], shape=(1417,))

In [130]:
model = MultinomialNB()

In [131]:
model.fit(xtrain, ytrain)

MultinomialNB()

In [132]:
ypred = model.predict(xtest)

In [133]:
accuracy_score(ytest, ypred)

0.6563380281690141

In [134]:
confusion_matrix(ytest, ypred)

array([[ 19,  37,  22],
       [  1, 142,  20],
       [  1,  41,  72]])

In [143]:
caption = "This was the worst experience I've ever had — absolutely terrible in every possible way and completely unacceptable."

caption_processed = preprocessText(caption)

caption_processed

'worst experience ever absolutely terrible every possible way completely unacceptable'

In [144]:
caption_processed_vect = vectorizer.transform([caption_processed])

caption_processed_vect

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (1, 626)>

In [145]:
ypred = model.predict(caption_processed_vect)

ypred

array([2])

In [146]:
list(encoder.inverse_transform(ypred))

['positive']